
version: '3'

services:
  scholawrite:
    build:
      context: .
      dockerfile: Dockerfile.scholawrite
    depends_on:
      - mongo
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: App.py
      MONGO_HOST: mongo
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    networks:
      - scholawrite_network

  ngrok_schola:
    #image: ngrok/ngrok:alpine
    build:
      context: .
      dockerfile: Dockerfile.ngrok
    depends_on:
      - scholawrite
    #environment:
      #NGROK_AUTH_TOKEN: ${SCHOLA_NGROK_AUTH_TOKEN}
    networks:
      - scholawrite_network
    volumes:
      - ./ngrok_schola.yml:/root/.ngrok2/ngrok.yml
    ports:
      - "4041:4040"
    command: ["ngrok", "http", "scholawrite:5000", "--host-header=scholawrite:5000", "--domain=scholawrite.ngrok.app", "--log=stdout", "--log-level=debug"]

  admin_page:
    build:
      context: .
      dockerfile: Dockerfile.admin_page
    environment:
      FLASK_APP: admin.py
      MONGO_HOST: mongo
    networks:
      - scholawrite_network
    ports:
      - "5200:5200"

  ngrok_admin:
    #image: ngrok/ngrok:alpine    
    build:
      context: .
      dockerfile: Dockerfile.ngrok
    depends_on:
      - admin_page
    volumes:
      - ./ngrok_admin.yml:/root/.ngrok2/ngrok.yml
    #environment:
      #NGROK_AUTH_TOKEN: ${ADMIN_NGROK_AUTH_TOKEN}
    networks:
      - scholawrite_network
    ports:
      - "4040:4040"
    command: ["ngrok", "http", "admin_page:5200", "--host-header=admin_page:5200", "--domain=dominant-publicly-urchin.ngrok-free.app", "--log=stdout", "--log-level=debug"]


  mongo:
    image: "mongo:latest"
    ports:
      - "5001:27017"
    volumes:
      - mongodbdata:/data/db
    networks:
      - scholawrite_network

networks:
  scholawrite_network:
    driver: bridge

volumes:
  mongodbdata:
