FROM ubuntu:20.04

RUN apt-get update -y && \
    apt-get install -y curl gnupg
RUN  curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | tee /etc/apt/sources.list.d/ngrok.list

RUN apt-get update -y && \
    apt-get install ngrok
